### PR TITLE
CONSOLE-3722: upgrade Cypress and switch default browser to Electron

### PR DESCRIPTION
**Pull request by rhamilto**

### CODE REVIEW

**Comment by rhamilto** [comment]
@cyril-ui-developer, PTAL

**Review by TheRealJon — APPROVED** [review]
/lgtm

**Review by jhadvig — APPROVED** [review]
/lgtm
/approve

**Comment by rhamilto** [comment]
@spadgett, mind approving?  Looks like we need to update [the approvers list](https://github.com/openshift/console-plugin-template/blob/main/OWNERS).

**Comment by jcaianirh** [comment]
> @spadgett, mind approving? Looks like we need to update [the approvers list](https://github.com/openshift/console-plugin-template/blob/main/OWNERS).

cc: @vojtechszocs you're also on the approver list, if you could take a look that would be great.

**Review by spadgett — APPROVED** [review]
/approve

**Pull request merged**
